version: '3.9'

services:
  app:
    container_name: solveq-task-dev
    build:
      target: dev
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: npm run dev
