version: '3.9'

services:
  app:
    build:
      context: .
    environment:
      - APP_MYSQL_HOST=db
      - APP_MYSQL_PORT=3306
      - APP_MYSQL_USERNAME=user
      - APP_MYSQL_PASSWORD=password
      - APP_MYSQL_DATABASE=task
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: solveq-task-db
    image: mysql/mysql-server:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=task
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db-entrypoint.sql:/docker-entrypoint-initdb.d/db-entrypoint.sql
      - ./db-data.sql:/db-data.sql
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
